### ISSUE TITLE
Replace Map destructuring with property destructuring

### ISSUE THREAD

**Issue by seaneagan** [DirectMyFile/dep-destructuring#1]
Map destructuring based on String map keys won't work well with dart2js minification, because it will require the variable names to be retained.

Something more useful which doesn't suffer from this problem would be property destructuring which assigns properties from objects to variables of the same name.  Example:

var {isEmpty, length} = {};
assert(isEmpty == true);
assert(length == 0);

This should also be more statically analyzable.

**Comment by azenla** [comment]
I'll update it to this later :) I like this a lot better

**Comment by seaneagan** [comment]
In general, I would recommend looking at ES 6 for inspiration for this proposal:

http://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-assignment

**Comment by azenla** [comment]
Just remembered something. The compiler would still be minifying the variable names, but not the map keys. This is not a big deal, because it would probably just transform it into it's counterpart. See this:

``` dart
/// With this Proposal
var {a, b} = {
  "a": 1,
  "b": 2
};

/// Without this Proposal
var tmp = {
  "a": 1,
  "b": 2
};

var a = tmp["a"];
var b = tmp["b"];
```

It would transform the code into the example without the proposal and then continue compilng.

**Comment by azenla** [comment]
What if we had both property and map destructuring?

**Comment by seaneagan** [comment]
that's assuming `tmp` is a `const` `Map`.  In general it won't be `const`, and thus dart2js won't be able to generate this code:

``` dart
var {a, b} = mapWithDynamicKeys;
var a = tmp["a"];
var b = tmp["b"];
```

**Comment by seaneagan** [comment]
Well, it will, but the point is it will still have to retain the variable names for use within e.g. `tmp["a"]`.

**Comment by seaneagan** [comment]
And the thing that makes property destructuring more useful is that all objects have properties, while only some happen to implement `Map<String, ?>`, and property extraction is also more performant than hashing, so we don't want to encourage unnecessary hashing.

**Comment by azenla** [comment]
Ok

**Comment by xxgreg** [comment]
I think destructing assignment probably needs to be considered in parallel with something similar to C#'s anonymous types. For example in Dart this would look like:

``` dart
foo() => new {a: 42, b: 'blah'};
main() { var {a, b} = foo(); }
```

This is basically a shorthand for:

``` dart

/// Auto-generated in the example above.
class Bar { Bar({this.a, this.b});  final a; final b; }

Bar foo() => new Bar(42, 'blah');

main() { var {a, b} = foo(); }
```

Also consider how types will be specified. I believe typescript does it like this: 

```
 var {a : int, b : String } = foo();
```

Another problem is making sure that the new syntax doesn't introduce ambiguities into the language.

**Comment by azenla** [comment]
That's my next goal, typing.

**Comment by azenla** [comment]
@xxgreg I'll make a new DEP for the anonymous types.
