### ISSUE TITLE
Don't use same syntax for different destructurings.

### ISSUE THREAD

**Issue by lrhn** [DirectMyFile/dep-destructuring#2]
The current syntax is `{a, b} = o` and does different things depending on the runtime type of `o`. If `o` is a map, it desugars to `var tmp=o;a = tmp["a"];b = tmp["b"];`. If `o` is a list, it desugars to `var tmp=o; a = tmp[0]; b = tmp[1];`. Otherwise it desugars to `var tmp = o;a = tmp.a;b = tmp.b;`.

However, you don't actually know the type of `o` until runtime, so you have to desugar into something containing two type tests and all the assignments. And that's not even taking into account that some object may be both a list and a map - and you might still want the third type of access.

How about instead:

``` dart
var (a, b) = o;  // a = o.a; b = o.b;
var [a, b] = o;  // a = o[0]; b = o[1];
var {a, b} = o;  // a = o["a"]; b = o["b"];
```

That has the advantage of the user saying which version you want, and it doesn't depend on the runtime type. That would allow you to do destructuring on anything with an index operator, whether it's a list or not: `var (a, b) = "xy"; assert(a == "x"); assert(b == "y");`.

**Comment by azenla** [comment]
I'm going to rewrite it to be this:

Lists:

``` dart
var [a, b] = [1, 2];
```

Properties and Maps:

``` dart
var {a, b} = new Point(5, 1);
```

**Comment by lrhn** [comment]
Conflating map access and property access still suffers from the problem that `{a, b} = o;` needs to know if `o` is a Map before deciding on whether to do `a = o.a` or `a = o[#a]`, and you get into trouble if you ever have a class that is a Map and also has `a` and `b` properties. For example; `{runtimeType, hashCode} = o`, is that going to do property or map lookup on `o`?

**Comment by azenla** [comment]
Ok, I'm dropping map destructuring them, that sound good @lrhn?

**Comment by lrhn** [comment]
It's probably a safe place to start. The only common use-case I see for map destructuring is interacting with JSON data, and that would require string keys anyway.
