### ISSUE TITLE
Consider whether Map-destructuring makes sense.

### ISSUE THREAD

**Issue by lrhn** [DirectMyFile/dep-destructuring#3]
Maps are destructured so that `{a, b} = o;` becomes `a = o["a"];b = o["b"];`.
I'm not entirely sure I like that since it converts variable names to strings. That feels slightly arbitrary. It could also do `a = o[#a];b = o[#b];` instead of using strings as keys. I'd probably prefer that, even if it's less likely to be useful.
In JavaScript, object keys/properties are always strings, so it makes sense to destructure on those, but in Dart, that role is played by member names, not map keys.

**Comment by azenla** [comment]
Ok, @lrhn, Using symbols would make reflection easier, I'll do that. I wish I could do better, but multiple people have raised this issue, so I'll solve it like that.

If you feel it should be removed all together @lrhn, let me know :)
