### ISSUE TITLE
Extra type using `: type` isn't Dart style.

### ISSUE THREAD

**Issue by lrhn** [DirectMyFile/dep-destructuring#4]
It's suggested that the types of individual variables can be given as `{a : int, b : String} = o;`.
That's (sadly) not how Dart writes types.
Maybe instead allow:

``` dart
var {a, b} = o;
{var a, var b} = o;
{int a, String b} = o;
```

where the first line is shorthand for the second, and the third line is how to give a non-dynamic type to the variables.

Maybe even allow:

``` dart
String {a, b} = o
```

as shorthand for 

``` dart
{String a, String b} = o;
```

just as you can write `String a, b, c;` to declare multiple variables.

This also allows you to do:

``` dart
int a;
{a, String b} = o;
```

to only declare `b` in the destructuring, but use a pre-declared `a`.

**Comment by azenla** [comment]
I'll rewrite this. I wrote the typing stuff at 1 AM, so I wasn't thinking through it enough :)
