### ISSUE TITLE
What is the type of these new eassignments

### ISSUE THREAD

**Issue by gbracha** [DirectMyFile/dep-destructuring#8]
In Dart, an assignment is an expression. 

x = 3; // value is 3; static type is int, irrespective of type of x

Given

x, y = [1, 2]; 

what is its value?  Presumably [1, 2]. And its type is presumably List.  In other words, the assignment evaluates to its right hand side, and assigns variables as a side effect.

**Comment by azenla** [comment]
@gbracha The result of the expression is equal to the right side of the expression. I will add this note to the proposal.
