### ISSUE TITLE
Destructuring of objects

### ISSUE THREAD

**Issue by gbracha** [DirectMyFile/dep-destructuring#9]
The examples show destructuring with general objects on the right had side.  What fields of the right hand side are used, and in what order? For example, are inherited fields accessed? Are private fields accessed? (hopefully not, otherwise privacy is violated; or maybe only fields accessible at the point of assignment; but determining that might be costly) Do we distinguish fields from getters (better not, Dart is designed for representation independence)? So, do we iterate thru all public getters? How do we know what those are? It seems a bit like reflection; could be costly.

What if the left hand side has more (or less) variables that denoted by the right hand side? Is that an runtime error? Is it a warning or a compile-time error? Are extra variables set to null?
What if the layout of the class of object used changes over time?

I'm very skeptical of this part of the proposal.

**Comment by azenla** [comment]
@gbracha I'll address a few things here that I will add to the proposal.

Destructuring of objects is designed to be easily translated into the current syntax:

``` dart
var {x, y} = new Point(5, 1);
```

translates to

``` dart
var tmp = new Point(5, 1);
var x = tmp.x;
var y = tmp.y;
```

This also means that privacy is respected, and everything is just as if it were not using the proposal.
The variable names correspond to the properties of the object. I am sorry for not making this clear. This means that it is easily statically analyzable. The order in this case does not affect the state of the variables in the next statement. For instance:

``` dart
var {isEmpty, length} = {};
```

is the same as doing:

``` dart
var {length, isEmpty} = {};
```

For list destructuring, variables are assigned left to right starting with the index 0 and going up on each identifier. It should be a runtime error if the left hand side goes out of bounds.

Any concerns you have, please do let me know. I have very little experience of language design, I have only ever created one language, and it was just for fun.
